version: "3.9"

services:
  node:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: react-test-node
    ports:
      - 3000:3000
      - "3001:3001"
    volumes:
    - ./:/usr/src/app
    command: sh -c "cd react-test-node && yarn start"
    stdin_open: true
    tty: true

volumes:
  node-modules:
